#
# You need to specify the base URL if you want to use virtual-host-style addressing,
# like 'https://bucketname.yourdomain.org'
#
#base_url: https://yourdomain.org

#
# Loguru logging level (ERROR, WARNING, INFO, DEBUG, TRACE)
#
log_level: INFO

#--------------------------------------------------------------------------------------
# The list of target storage locations to serve
#--------------------------------------------------------------------------------------
targets:

  #
  # The 'file' client serves data from any local file path
  #
  - name: local_files
    client: file
    options:
      root: .

  #
  # Exposes s3://janelia-cosem-datasets at /cosem-data
  #
  - name: cosem-data
    client: aioboto
    options:
      bucket: janelia-cosem-datasets

  #
  # Exposes s3://janelia-cosem-datasets/aic_desmosome-1 at /cosem-data-with-prefix
  # using the default client (currently aioboto).
  #
  - name: cosem-data-with-prefix
    prefix: aic_desmosome-1
    options:
      bucket: janelia-cosem-datasets

  #
  # Exposes s3://janelia-cosem-datasets at /cosem-data-hidden
  # using the default client (currently aioboto) and makes it unbrowseable
  #
  - name: cosem-data-hidden
    hidden: true
    options:
      bucket: janelia-cosem-datasets

  # To serve data from a private bucket, you must configure an access key and secret key as
  # demonstrated below. This example also shows how to use a custom endpoint.
  #
  #- name: multifish
  #  options:
  #    endpoint: https://s3.us-east-1.lyvecloud.seagate.com/
  #    bucket: multifish
  #    access_key_path: './var/lyve_access_key'
  #    secret_key_path: './var/lyve_secret_key'
