services:

  nginx:
    image: nginx
    container_name: jproxy_nginx
    restart: unless-stopped
    depends_on:
      - jproxy
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CERT_FILE}:/certs/default.crt:ro
      - ${KEY_FILE}:/certs/default.key:ro
      - ${NGINX_CACHE_DIR}:/var/cache/nginx

  jproxy:
    image: ghcr.io/janeliascicomp/jproxy:0.2.0
    restart: unless-stopped
    ports:
      - 8000
    volumes:
      - ${CONFIG_FILE}:/app/jproxy/config.yaml
      - ${VAR_DIR}:/app/jproxy/var
