name: jproxy
services:

    webapp:
        image: ghcr.io/janeliascicomp/jproxy:0.1.0
        ports:
          - 443:8000
        restart: unless-stopped
        volumes:
          - ${CONFIG_FILE}:/app/jproxy/config.yaml
          - ${VAR_DIR}:/app/jproxy/var
          - ${CERT_FILE}:/certs/default.crt
          - ${KEY_FILE}:/certs/default.key
