name: Pylint

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint   
    - name: Test with pytest
      run: |
        python -m pytest --cov=jproxy --cov-report=html --cov-report=term -W ignore::DeprecationWarning --html=test_results.html
    - name: Upload pytest and coverage results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: testcoverage-${{ matrix.os }}-py${{ matrix.python-version }}
        path: |
          htmlcov/*
          test_results.html
          retention-days: 7
